// Desactivado en prototipo — requiere assets GLB y Three.js
export function CaseModel()         { return null }
export function MotherboardModelReal() { return null }
export function CpuModelReal()      { return null }
export function GpuAmdModel()       { return null }
export function GpuNvidiaModel()    { return null }
export function RamModelReal()      { return null }
export function PsuModelReal()      { return null }
export function PsuAltModel()       { return null }
export function CoolerModelReal()   { return null }
export function StorageKingstonModel() { return null }
export function StorageSamsungModel()  { return null }
export function PartModel()         { return null }
export function CpuModelPlaceholder()  { return null }
export function GpuModelPlaceholder()  { return null }
export function RamModelPlaceholder()  { return null }
export function StorageModelPlaceholder() { return null }
export function PsuModelPlaceholder()  { return null }
export function MotherboardModelPlaceholder() { return null }
export function CoolerModelPlaceholder() { return null }
